export const GROQ_TRANSACTION_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: [
    'tipo',
    'valor',
    'moeda',
    'data_transacao',
    'hora_transacao',
    'pagador',
    'recebedor',
    'chave_pix',
    'tipo_transferencia',
    'id_transacao',
    'codigo_autenticacao',
    'numero_controle',
    'banco_emissor',
    'situacao',
    'descricao',
    'confianca',
    'fonte_extracao',
    'campos_duvidosos',
  ],
  properties: {
    tipo: { type: 'string', enum: ['receita', 'gasto'] },
    valor: { type: 'string' },
    moeda: { type: 'string', enum: ['BRL', 'nao identificado'] },
    data_transacao: { type: 'string' },
    hora_transacao: { type: 'string' },
    pagador: {
      type: 'object',
      additionalProperties: false,
      required: ['nome', 'documento', 'instituicao'],
      properties: {
        nome: { type: 'string' },
        documento: { type: 'string' },
        instituicao: { type: 'string' },
      },
    },
    recebedor: {
      type: 'object',
      additionalProperties: false,
      required: ['nome', 'documento', 'instituicao'],
      properties: {
        nome: { type: 'string' },
        documento: { type: 'string' },
        instituicao: { type: 'string' },
      },
    },
    chave_pix: { type: 'string' },
    tipo_transferencia: { type: 'string' },
    id_transacao: { type: 'string' },
    codigo_autenticacao: { type: 'string' },
    numero_controle: { type: 'string' },
    banco_emissor: { type: 'string' },
    situacao: { type: 'string' },
    descricao: { type: 'string' },
    confianca: { type: 'string', enum: ['alta', 'media', 'baixa'] },
    fonte_extracao: { type: 'string', enum: ['local', 'groq', 'local+groq'] },
    campos_duvidosos: { type: 'array', items: { type: 'string' } },
  },
} as const;
